# Generated by Django 4.0.3 on 2022-04-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0003_alter_charity_charity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefactorsStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='beneficiary/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donationApp.charity')),
            ],
        ),
    ]
