# Generated by Django 4.0.3 on 2022-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0004_benefactorsstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactorsstories',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='benefactorsstories',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
