# Generated by Django 4.0.3 on 2022-04-05 05:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0005_alter_benefactorsstories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactorsstories',
            name='user_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
