# Generated by Django 4.0.3 on 2022-04-05 09:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0006_alter_benefactorsstories_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
