# Generated by Django 4.0.3 on 2022-04-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0007_alter_charity_charity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='charity_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='charities/'),
        ),
    ]
