# Generated by Django 4.0.3 on 2022-04-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0010_rename_benefactorsstories_benefactorsstory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charity',
            old_name='users',
            new_name='charity',
        ),
    ]
